promatil:
  config:
    clients:
      - url: http://loki-gateway/loki/api/v1/push
        tenant_id: 1
loki:
  chunksCache:
    allocatedMemory: 200
  resultsCache:
    allocatedMemory: 200
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    storage:
      type: s3
      bucketNames:
        chunks: monitoring-loki-chunks
        ruler: monitoring-loki-ruler
        admin: monitoring-loki-admin
      s3:
        endpoint: s3.yandexcloud.net
        secretAccessKey: "${SECRET_KEY}"
        accessKeyId: ${ACCESS_KEY}
        s3ForcePathStyle: false
        insecure: false
    schemaConfig:
      configs:
      - from: 2024-04-01
        object_store: s3
        store: tsdb
        schema: v13
        index:
          prefix: index_
          period: 24h
    extraArgs:
      - "-config.expand-env=true"
    extraEnv:
      - name: SECRET_KEY
        valueFrom:
          secretKeyRef:
            name: s3
            key: secret_key
      - name: ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: s3
            key: access_key

